#pragma once

// This file is meant to be generated by midi2array2.py (--out-header).
// Example:
//   python midi2array2.py "debussy-clair-de-lune.mid" --steps-per-beat 4 --mode onset --out-header PianoStrip/Songs.h

struct Song {
  const char* name;
  const char* const* steps;
  size_t stepCount;
  float stepSeconds;
};

static const char* const kSong_Empty[] = {
  ""
};

static const Song kSongs[] = {
  {
    "Empty",
    kSong_Empty,
    sizeof(kSong_Empty) / sizeof(kSong_Empty[0]),
    0.12f
  }
};

static const size_t kSongCount = sizeof(kSongs) / sizeof(kSongs[0]);
